"""
SQLAlchemy database models for FOREX AI Trading Bot.
Defines tables for market data, signals, positions, and trade history.
"""

from datetime import datetime
from enum import Enum as PyEnum

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship

from shared.database import Base


class SignalType(str, PyEnum):
    """Trading signal types."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class PositionStatus(str, PyEnum):
    """Position status types."""
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    PENDING = "PENDING"


class MarketData(Base):
    """
    OHLCV market data from OANDA.
    TimescaleDB hypertable for time-series optimization.
    """
    __tablename__ = "market_data"
    __table_args__ = {"schema": "trading"}

    id = Column(Integer, primary_key=True, index=True)
    instrument = Column(String(20), nullable=False, index=True)  # EUR_USD, GBP_USD, etc.
    timeframe = Column(String(10), nullable=False, index=True)  # M1, M5, M15, H1, H4, D
    timestamp = Column(DateTime, nullable=False, index=True)

    # OHLCV data
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Integer, nullable=False)

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Composite index for efficient queries
    __table_args__ = (
        Index("ix_market_data_instrument_timeframe_timestamp",
              "instrument", "timeframe", "timestamp"),
        {"schema": "trading"}
    )

    def __repr__(self):
        return f"<MarketData {self.instrument} {self.timeframe} {self.timestamp}>"


class Signal(Base):
    """
    Trading signals generated by ML models or LLM.
    """
    __tablename__ = "signals"
    __table_args__ = {"schema": "trading"}

    id = Column(Integer, primary_key=True, index=True)
    instrument = Column(String(20), nullable=False, index=True)
    timestamp = Column(DateTime, nullable=False, index=True)

    # Signal details
    signal_type = Column(Enum(SignalType), nullable=False)
    confidence = Column(Float, nullable=False)  # 0.0 to 1.0

    # Source information
    source = Column(String(50), nullable=False)  # "ml_random_forest", "llm_gpt4", etc.
    model_version = Column(String(20))

    # Technical indicators (snapshot at signal time)
    indicators = Column(JSONB)  # Store RSI, MACD, EMA, etc. as JSON

    # Price context
    entry_price = Column(Float)
    stop_loss = Column(Float)
    take_profit = Column(Float)

    # Execution status
    executed = Column(Boolean, default=False, nullable=False)
    execution_timestamp = Column(DateTime)

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationship to positions
    positions = relationship("Position", back_populates="signal")

    def __repr__(self):
        return f"<Signal {self.signal_type} {self.instrument} conf={self.confidence:.2f}>"


class Position(Base):
    """
    Trading positions (open and closed).
    """
    __tablename__ = "positions"
    __table_args__ = {"schema": "trading"}

    id = Column(Integer, primary_key=True, index=True)
    signal_id = Column(Integer, ForeignKey("trading.signals.id"), index=True)
    instrument = Column(String(20), nullable=False, index=True)

    # Position details
    status = Column(Enum(PositionStatus), nullable=False, default=PositionStatus.PENDING)
    side = Column(Enum(SignalType), nullable=False)  # BUY or SELL
    units = Column(Integer, nullable=False)  # Position size

    # Entry details
    entry_price = Column(Float, nullable=False)
    entry_timestamp = Column(DateTime, nullable=False)

    # Exit details (null if still open)
    exit_price = Column(Float)
    exit_timestamp = Column(DateTime)

    # Risk management
    stop_loss = Column(Float)
    take_profit = Column(Float)

    # P&L tracking
    realized_pnl = Column(Float)  # Profit/Loss in account currency
    unrealized_pnl = Column(Float)  # Current P&L for open positions

    # OANDA trade ID
    oanda_trade_id = Column(String(100), unique=True, index=True)

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    signal = relationship("Signal", back_populates="positions")
    trade_history = relationship("TradeHistory", back_populates="position")

    __table_args__ = (
        Index("ix_positions_status_instrument", "status", "instrument"),
        {"schema": "trading"}
    )

    def __repr__(self):
        return f"<Position {self.side} {self.instrument} {self.status}>"


class TradeHistory(Base):
    """
    Detailed execution history and events for positions.
    Audit trail for all trading activity.
    """
    __tablename__ = "trade_history"
    __table_args__ = {"schema": "trading"}

    id = Column(Integer, primary_key=True, index=True)
    position_id = Column(Integer, ForeignKey("trading.positions.id"), nullable=False, index=True)
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow, index=True)

    # Event details
    event_type = Column(String(50), nullable=False)  # "ENTRY", "EXIT", "STOP_LOSS", "TAKE_PROFIT", "MODIFY"
    description = Column(Text)

    # Price information
    price = Column(Float)
    units = Column(Integer)

    # Execution details
    oanda_transaction_id = Column(String(100))
    execution_details = Column(JSONB)  # Full response from OANDA

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationship
    position = relationship("Position", back_populates="trade_history")

    def __repr__(self):
        return f"<TradeHistory {self.event_type} pos={self.position_id}>"


class LLMAnalysis(Base):
    """
    ChatGPT strategic analysis results.
    Daily market regime detection and performance insights.
    """
    __tablename__ = "llm_analysis"
    __table_args__ = {"schema": "trading"}

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, nullable=False, index=True)

    # Analysis type
    analysis_type = Column(String(50), nullable=False)  # "regime", "sentiment", "performance", "correlation"

    # Input data sent to LLM
    prompt = Column(Text, nullable=False)
    market_data_summary = Column(JSONB)  # Aggregated indicators, price changes

    # LLM response
    response = Column(Text, nullable=False)
    parsed_result = Column(JSONB)  # Structured extraction from response

    # Model details
    model = Column(String(50), nullable=False)  # "gpt-4o-mini"
    tokens_used = Column(Integer)
    cost = Column(Float)

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    __table_args__ = (
        Index("ix_llm_analysis_type_timestamp", "analysis_type", "timestamp"),
        {"schema": "trading"}
    )

    def __repr__(self):
        return f"<LLMAnalysis {self.analysis_type} {self.timestamp}>"
