"""Initial schema with market_data, signals, positions, trade_history, llm_analysis

Revision ID: 33fe8dda15a8
Revises: 
Create Date: 2025-12-29 04:47:27.459043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33fe8dda15a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('market_data_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('parsed_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_llm_analysis_type_timestamp', 'llm_analysis', ['analysis_type', 'timestamp'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_llm_analysis_id'), 'llm_analysis', ['id'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_llm_analysis_timestamp'), 'llm_analysis', ['timestamp'], unique=False, schema='trading')
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_market_data_instrument_timeframe_timestamp', 'market_data', ['instrument', 'timeframe', 'timestamp'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_market_data_id'), 'market_data', ['id'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_market_data_instrument'), 'market_data', ['instrument'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_market_data_timeframe'), 'market_data', ['timeframe'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_market_data_timestamp'), 'market_data', ['timestamp'], unique=False, schema='trading')
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('signal_type', sa.Enum('BUY', 'SELL', 'HOLD', name='signaltype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('execution_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index(op.f('ix_trading_signals_id'), 'signals', ['id'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_signals_instrument'), 'signals', ['instrument'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_signals_timestamp'), 'signals', ['timestamp'], unique=False, schema='trading')
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('instrument', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'PENDING', name='positionstatus'), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', 'HOLD', name='signaltype'), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_timestamp', sa.DateTime(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('oanda_trade_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['trading.signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index('ix_positions_status_instrument', 'positions', ['status', 'instrument'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_positions_id'), 'positions', ['id'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_positions_instrument'), 'positions', ['instrument'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_positions_oanda_trade_id'), 'positions', ['oanda_trade_id'], unique=True, schema='trading')
    op.create_index(op.f('ix_trading_positions_signal_id'), 'positions', ['signal_id'], unique=False, schema='trading')
    op.create_table('trade_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('oanda_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('execution_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['trading.positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trading'
    )
    op.create_index(op.f('ix_trading_trade_history_id'), 'trade_history', ['id'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_trade_history_position_id'), 'trade_history', ['position_id'], unique=False, schema='trading')
    op.create_index(op.f('ix_trading_trade_history_timestamp'), 'trade_history', ['timestamp'], unique=False, schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_trade_history_timestamp'), table_name='trade_history', schema='trading')
    op.drop_index(op.f('ix_trading_trade_history_position_id'), table_name='trade_history', schema='trading')
    op.drop_index(op.f('ix_trading_trade_history_id'), table_name='trade_history', schema='trading')
    op.drop_table('trade_history', schema='trading')
    op.drop_index(op.f('ix_trading_positions_signal_id'), table_name='positions', schema='trading')
    op.drop_index(op.f('ix_trading_positions_oanda_trade_id'), table_name='positions', schema='trading')
    op.drop_index(op.f('ix_trading_positions_instrument'), table_name='positions', schema='trading')
    op.drop_index(op.f('ix_trading_positions_id'), table_name='positions', schema='trading')
    op.drop_index('ix_positions_status_instrument', table_name='positions', schema='trading')
    op.drop_table('positions', schema='trading')
    op.drop_index(op.f('ix_trading_signals_timestamp'), table_name='signals', schema='trading')
    op.drop_index(op.f('ix_trading_signals_instrument'), table_name='signals', schema='trading')
    op.drop_index(op.f('ix_trading_signals_id'), table_name='signals', schema='trading')
    op.drop_table('signals', schema='trading')
    op.drop_index(op.f('ix_trading_market_data_timestamp'), table_name='market_data', schema='trading')
    op.drop_index(op.f('ix_trading_market_data_timeframe'), table_name='market_data', schema='trading')
    op.drop_index(op.f('ix_trading_market_data_instrument'), table_name='market_data', schema='trading')
    op.drop_index(op.f('ix_trading_market_data_id'), table_name='market_data', schema='trading')
    op.drop_index('ix_market_data_instrument_timeframe_timestamp', table_name='market_data', schema='trading')
    op.drop_table('market_data', schema='trading')
    op.drop_index(op.f('ix_trading_llm_analysis_timestamp'), table_name='llm_analysis', schema='trading')
    op.drop_index(op.f('ix_trading_llm_analysis_id'), table_name='llm_analysis', schema='trading')
    op.drop_index('ix_llm_analysis_type_timestamp', table_name='llm_analysis', schema='trading')
    op.drop_table('llm_analysis', schema='trading')
    # ### end Alembic commands ###
